### PR TITLE
feat(eventPage): add pictures of event from api

### PR DESCRIPTION
**Pull request by Slashgear**
## 🤔 Why do you want to make those changes?

Let's add our picture from meetup API in event page 

## 🧑‍🔬 How did you make them?

- change type event
- add image
- simple image row for now.
- I may consider adding murri grid of picture 

## 🧪 How to check them?

- check event page

### CODE REVIEW

**Review by mathieumure — APPROVED** [review]

**Comment by CruuzAzul** [comment]
image

**Comment by Slashgear** [comment]
Small forgotten CSP rule, fixed now @CruuzAzul

**Comment by Slashgear** [comment]
@jsulpis Do you think adding a muuri grid of picture could be better here ? :)

**Comment by jsulpis** [comment]
> image

@mathieumure @CruuzAzul now you understand why showing scrollbars on MacOS is important ? 😅

@Slashgear I suggest to always use `overflow: auto` instead of `overflow: scroll` unless you have a good reason 😉

**Pull request merged**
